server:
  port: 8086
spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/shopzone_notifications
    username: shopzone_admin
    password: shopzone_secret_2024
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USERNAME:your_mailtrap_username}
    password: ${MAIL_PASSWORD:your_mailtrap_password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

shopzone:
  app:
    name: ShopZone
    url: ${APP_BASE_URL:http://localhost:3000}
  email:
    from: ${MAIL_FROM:noreply@shopzone.com}

logging:
  level:
    com.shopzone.notificationservice: DEBUG
